### user
POST http://localhost:3001/api/user
content-type: application/json

{
  "name": "testUser",
  "username": "test",
  "password": "testPasswordHash"
}

###login
POST http://localhost:3001/api/login
content-type: application/json

{
  "username": "test",
  "password": "testPasswordHash"
}

###
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0YWQ5YmJkMGE5MTQyYzJhYjkxYWI2NCIsImlhdCI6MTY4OTEwMjg3NH0.9wG94Y2FHIyoGw7Kc-IuDOCLMzp496VcgC2Yc-NBvtU

{
  "title": "test1",
  "author": "author1",
  "url": "wadkbawda",
  "likes": 2
}

###
GET http://localhost:3001/api/blogs
content-type: application/json