GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/6489bc3041e4b2299f96d16b

###
DELETE http://localhost:3001/api/persons/4

### Same name
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arto Hellas 2",
  "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arto Hellas 2"
}